### ISSUE TITLE
请问mail要怎么配置？

### ISSUE THREAD

**Issue by bonbonx01** [rymcu/forest#154]
在.yml中配置：  
mail:
    host: smtp.163.com # 网站发送邮件邮箱服务 host
    port: 465
    username: service@rymcu.com
    password: 4W3tCXdyk0Gm

但是会报错javax.mail.MessagingException: Got bad greeting from SMTP host: smtp.163.com, port: 465, response: [EOF]
请问怎么解决？
<img width="1138" alt="Snipaste_2023-12-29_11-32-08" src="https://github.com/rymcu/forest/assets/128836715/ec503eb1-c2f8-437e-8931-a85b00cc4450">

**Comment by ronger-x** [comment]
常规的邮箱配置, 自行百度一下
