### ISSUE TITLE
请问实现yuumi功能是否需要增加其他配置？

### ISSUE THREAD

**Issue by leto-hub** [rymcu/forest#162]
目前直接运行该功能，点击发送后，后端显示timeout。
是否未能成功调用chatGPT api？
<img width="700" alt="image" src="https://github.com/rymcu/forest/assets/71166057/03787267-e24a-465d-b5d7-2f77891ad724">

**Comment by ronger-x** [comment]
默认是调用 OpenAI  的地址, 需要自选配置代理

![image](https://github.com/rymcu/forest/assets/29698602/2a237c41-17cd-4bd8-92a8-0c68cf50e964)
