### ISSUE TITLE
使用JAR部署在服务器时启动失败，application Context属性未注入

### ISSUE THREAD

**Issue by taoyuanping** [rymcu/forest#179]
修改成JAR部署，使用内嵌的tomcat运行，本地IDE环境运行正常，打包后在服务器上运行，启动失败，提示`application Context属性未注入, 请在applicationContext.xml中定义SpringContextHolder.`，UploadController里获取env时，赋值到了静态成员变量上，获取时SpringContextHolder还没有进行注入，我们也通过代理里提供的docker方式，运行却是正常的，是不是docker用到的的tomcat修改了哪些配置，延迟了静态变量的初始化，我们对此很好奇，不知道大家有没有遇到同样的情况

**Comment by acaterpillar** [comment]
直接 注入，不要写成变量，， @value， 或者@autowired
