### ISSUE TITLE
链接数据库失败了，提示没有配置url文件

### ISSUE THREAD

**Issue by laijianbo** [rymcu/forest#80]
项目运行遇到一个问题，提示Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.但是数据库配置文件又是配置好了的，而且我将配置文件复制到其他项目可以正常链接，就是这个项目不行，不知道什么原因

**Comment by ronger-x** [comment]
是否配置了资源文件目录

![image](https://user-images.githubusercontent.com/29698602/163656976-0e18471d-d2c7-4bed-ac57-56e5fff537df.png)

**Comment by laijianbo** [comment]
> 
非常感谢，确实是那个问题

**Comment by laijianbo** [comment]
但是启动 的时候创建索引报错了了，
![image](https://user-images.githubusercontent.com/10562738/163675583-50266e24-03a3-4952-a2d6-1148aefc7c67.png)

**Comment by ronger-x** [comment]
你可以更新至最新代码或者切换到 wx-dev 分支查看是否还存在问题,如还存在问题可以根据提示信息修改错误后提交 PR 或创建新的 issue 记录新的问题
