### ISSUE TITLE
轮播图两侧按钮遮挡文字

### ISSUE THREAD

**Issue by KKould** [rymcu/forest#96]
![image](https://user-images.githubusercontent.com/91525956/176910127-c771275a-00cd-4eea-8a6e-2b5a0be12855.png)

希望能将按钮隐藏或者外置两侧

**Comment by ronger-x** [comment]
已修改, [详见此链接](https://github.com/rymcu/nebula/commit/8aacd3933cd141e867dc47970a9a164b0f117f36)
