### ISSUE TITLE
你好请问下，启动项目之后无法访问首页

### ISSUE THREAD

**Issue by hezhuoyukuai** [rymcu/forest#98]
![image](https://user-images.githubusercontent.com/33505007/177932866-ec004354-d67a-4ec0-9bca-9b461304a4ae.png)
![image](https://user-images.githubusercontent.com/33505007/177932937-a78d4905-3aea-4575-a975-710fdd749212.png)

**Comment by KKould** [comment]
有部署前端项目吗，需要配套使用噢，前端nebula地址：https://github.com/rymcu/nebula
